# Generated by Django 5.1.6 on 2025-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0002_studentuser_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="studentnumber",
            new_name="year",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="appuser",
            name="email",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="password",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
