# Generated by Django 5.1.6 on 2025-03-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0005_remove_appuser_groups_remove_appuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="bio",
            field=models.TextField(default="blank"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="location",
            field=models.TextField(default="blank"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
