# Generated by Django 5.1.6 on 2025-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0007_alter_appuser_bio_alter_appuser_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
