# Generated by Django 5.1.6 on 2025-03-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0008_alter_appuser_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="bio",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
