# Generated by Django 5.1.6 on 2025-03-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0009_alter_appuser_bio_alter_appuser_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="bio",
        ),
    ]
