# Generated by Django 5.1.6 on 2025-03-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0010_remove_appuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
