# Generated by Django 5.1.6 on 2025-03-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0011_appuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="username",
            field=models.CharField(default="blank", max_length=255),
            preserve_default=False,
        ),
    ]
