# Generated by Django 5.1.6 on 2025-03-22 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appuser", "0012_appuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuser",
            name="password_reset_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="password_reset_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
