# Generated by Django 5.1.6 on 2025-03-24 22:43

from django.db import migrations, models
import uuid

def fix_duplicate_tokens(apps, schema_editor):
    AppUser = apps.get_model('appuser', 'AppUser')
    for user in AppUser.objects.all():
        user.email_verification_token = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0016_alter_appuser_email_verification_token"),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_tokens),
        migrations.AlterField(
            model_name="appuser",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
