# Generated by Django 5.1.6 on 2025-03-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0017_fix_duplicate_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
