# Generated by Django 5.1.6 on 2025-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0018_alter_appuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="year",
            field=models.IntegerField(default=1),
        ),
    ]
