# Generated by Django 5.1.6 on 2025-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0019_alter_appuser_location_alter_appuser_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
