# Generated by Django 5.1.6 on 2025-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0021_alter_appuser_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
