# Generated by Django 5.1.6 on 2025-03-25 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0022_alter_appuser_bio_alter_appuser_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
