# Generated by Django 5.1.6 on 2025-03-25 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0023_alter_appuser_email_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
