# Generated by Django 5.1.6 on 2025-04-02 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0024_alter_appuser_email_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
