# Generated by Django 5.1.6 on 2025-03-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Books", "Books"),
                    ("Sublets", "Sublets"),
                    ("Roommates", "Roommates"),
                    ("Rideshare", "Rideshare and Travel"),
                    ("Events", "Events"),
                    ("Other", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("Poor", "Poor"), ("Fair", "Fair"), ("Good", "Good")],
                max_length=255,
                null=True,
            ),
        ),
    ]
