# Generated by Django 5.1.6 on 2025-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_listing_category_alter_listing_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("BOOKS", "Books"),
                    ("SUBLETS", "Sublets"),
                    ("ROOMMATES", "Roommates"),
                    ("RIDESHARE", "Rideshare and Travel"),
                    ("EVENTS", "Events"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
