# Generated by Django 5.1.6 on 2025-04-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appuser", "0025_appuser_created_at"),
        ("listings", "0009_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="appuser.appuser",
            ),
        ),
    ]
